ELVIS-SOFTWARE/elvis

app/controllers/activity_ref_controller.rb, app/views/activity_ref/index.html.erb
modif activity_ref, affichage des familles d'activités, triées par ordre alphabétique
=> ELVIS-965-Tri-Famille

app/views/settings/plugin.html.erb
Bug footer sur la page de settings des plugin, fixed (</div> en trop)
=> ELVIS-889--Bug-Footer-PLugin

config/initializers/20-menu_generator.rb
Suppression du sous menu "liste des plugins"
=> ELVIS-973--plugis-sous-menu

frontend/components/plugins/PluginCard.js
=> ELVIS-975--plugin-text-card

app/views/payment_schedule/show.html.erb
Suppression de la mention "payable par ..."
=> ELVIS-993--Echeancier-print

app/views/devise/registrations/_registration.html.erb, app/views/devise/registrations/new.html.erb
Aligner les labels des champs sur la gauche
=> ELVIS-1005--Cosmetics-Inscription

frontend/components/parameters/Plannings/PlanningsParameters.js
Renommer l'onglet "Disponiblité des professeurs" par "Professeuers"
=> ELVIS-1011--Planning

frontend/components/planning/CreateActivityModal.js
Lors de la création d'un créneau, afficher phrase en fonction du select
=> ELVIS-964--Planning-dispo

frontend/components/PacksApplications/IncomingActivityInstances/upcomingActivityInstancesCards.js, frontend/components/PacksApplications/IncomingActivityInstances/upcomingActivityInstancesList.js, frontend/components/PacksApplications/MyActivities/activityCards.js, frontend/components/PacksApplications/MyActivities/myActivities.js, frontend/components/PacksApplications/MyActivities/placeholderCard.js, frontend/components/PacksApplications/MyActivities/regularActivityCards.js, frontend/packs/application.scss
=> ELVIS-1006-Pack-responsive-mobile

frontend/components/PacksApplications/IncomingActivityInstances/upcomingActivityInstancesList.js, frontend/components/PacksApplications/MyActivities/regularActivityCards.js
=> ELVIS-1013--Pack-card

app/controllers/my_activities_controller.rb, frontend/components/PacksApplications/BookActivityInstance/ActivityBooking.js, frontend/components/PacksApplications/BookActivityInstance/bookingCards.js
Affichage des cours complet et impossible pour l'élève de sélectionner le cours
=> ELVIS--1098-Pack-Inscription

frontend/components/PacksApplications/BookActivityInstance/ActivityBooking.js
Redirection vers "mes séances" une fois la séance rréservée
=> ELVIS--1029-Pack-redirection

frontend/components/parameters/Payments/AdhesionSettings.js
=> ELVIS--985-Adhesion-swal-text

frontend/components/activityApplications/Wizard.js
Redirection après inscription vers la page des activitées
=> ELVIS--1094-Pack-redirection

app/controllers/activity_ref_kind_controller.rb, frontend/components/activityRef/ActivityRefBasics.js
tri du select "famille" par ordre alphabétique
=> ELVIS--1034-activité-select

frontend/components/planning/ActivityDetailsModal.js
Trier la liste des activités par ordre alphabétique :
=> ELVIS--1108-Planning-sort

frontend/components/planning/SelectActivity.js
ajout d'un texte au place holder du select
=> ELVIS--1107-Planning-select

frontend/components/activityApplications/ActivityChoice.js
Dans le parcours d'inscription ajouter la durée lorsqu'elle est renseignée. Uniquement valable pour les activités et les packs
=> ELVIS-1100-Wizard-Duration

app/models/user.rb, frontend/components/activityApplications/UserSearch.js
modification du message d'erreur (personnalisé selon l'erreur commise)
=> ELVIS-1139-Inscription-message-erreur

frontend/components/common/AlertCheckbox.js, frontend/components/common/AlertYesNoRadio.js, frontend/components/common/Input.js, frontend/components/common/InputSelect.js, frontend/components/userForm/ConsentDocItem.js, frontend/components/userForm/ContactInfos.js, frontend/components/userForm/Fields.js, frontend/components/userForm/GeneralInfos.js, frontend/components/userForm/HandicapInfos.js, frontend/components/userForm/SelectSameAs.js, frontend/components/userForm/UserForm.js, frontend/tools/obj.js
=> ZIGGY-885--Wizard-Coordonnées

frontend/components/activityApplications/ActivityChoice.js, frontend/components/activityApplications/summary/Activity.js
ajout/modif de la durée des activités dans l'étape du wizard & affichage dans le select/demandes d'inscription
=> ELVIS-1131--Affichage-durée

app/controllers/users_controller.rb, app/models/user.rb, frontend/components/PreApplication.js, frontend/components/UserAvatar.js, frontend/components/activityItems/AnswerProposal.js, frontend/components/activityItems/CancelApplication.js, frontend/components/activityItems/CurrentActivityItem.js, frontend/components/activityItems/EditApplication.js, frontend/components/activityItems/NewActivityItem.js, frontend/components/activityItems/RenewActivityItem.js, frontend/components/activityItems/renderActivityAction.js
=> ELVIS-1141-Mes-Demandes-d'inscription

frontend/components/activityApplications/ActivityChoice.js
[Demande d'inscription] choix de l'activité modif
-  ajout d'espace entre le titre choix de l'activité et les filtres.
- plus de padding dans le bouton durée rechercher
- changer l'icone (cf maquette)
=> ELVIS-1146--Wizard-3-cosmetics

app/services/users/search_user.rb, frontend/components/UserAvatar.js, frontend/components/activityApplications/WizardUserSelectMember.js
=> ELVIS-1144--Inscription-1-design

frontend/components/PreApplication.js, frontend/components/activityItems/CurrentActivityItem.js
- Activités actuelles ne pas afficher la colonne séances restantes.
- Mettre le bouton arrêt à gauche et écrire sur le bouton s'arrêter.
=> ZIGGY-912--Demande-d'inscription-cosmetics

frontend/components/activityItems/renderActivityAction.js
En attente = en attente de traitement
=> ZIGGY-909--Demande-Inscription-libellés

frontend/components/activityApplications/Validation.js, frontend/components/activityApplications/Wizard.js, frontend/components/stepzilla.css, frontend/components/userForm/UserForm.js, frontend/inspinia/css/_buttons.scss, frontend/packs/application.scss
refonte graphique stepper et header d'inscription
=> ELVIS-1147--Stepzilla

app/views/activity_ref/index.html.erb
Page activité - ajout de la durée
Ajout de la durée sur l'encart de l'activité
=> (feat ELVIS-1156) fixed

app/controllers/activities_applications_controller.rb
=> ELVIS-1181

app/views/devise/registrations/_registration.html.erb
Lorsqu'un compte existe déjà l'information n'est pas indiqué à l'utilisateur.
Ajouter un message d'erreur en dessous du champ pour indiquer que le compte existe déjà.
"Un compte existe déjà avec cette adresse"
=> ELVIS-1158--Inscription-Compte-existant

app/models/activity_application.rb
If user lacks a level and if no NewStudentLevelQuestionnaire exists, create a new level (default level : "débutant") for the user
=> ZIGGY-939--Activity-Level

frontend/components/PacksApplications/MyActivities/myActivities.js, frontend/components/PacksApplications/UpcomingActivityInstances/upcomingActivityInstancesList.js, frontend/packs/application.scss
Modifier l'encart lorsqu'il n'y a pas de cours.
=> ELVIS-1171--Accueil-encart-cours

frontend/components/LoadingComponent.js
=> ELVIS-1170--Loader-User

frontend/components/activityItems/EditApplication.js, frontend/components/activityItems/NewActivityItem.js
erreur de validation lorsqu'un commentaire est soumis
=> ELVIS-1190-New-Application-Comments

frontend/components/PayerPaymentTerms.js, frontend/components/PayerPaymentTermsInfo.js, frontend/components/WrappedPayerPaymentTerms.js, frontend/components/activityApplications/UserSearch.js, frontend/components/activityApplications/Wizard.js, frontend/packs/application.scss
=> ELVIS-1189-Wizard-cosmetics

frontend/components/planning/ActivityDetailsModal.js
Lorsque l'école n'a qu'un lieu ne pas proposer de choisir le lieu mais prendre l'unique lieux par défaut
=> EMVIS-1161-Planning-select-lieu

app/controllers/activity_ref_controller.rb
trier le select famille par ordre alphabétique
=> feat (ELVIS-1034) ordre alphabétique select fixed

app/controllers/payments_controller.rb, frontend/components/userPayments/PaymentsSummary.js
Lorsqu'il n'y a qu'un tarif d'adhésion paramétrer : l'affecter par défaut
=> Elvis 1127  règlement adhésion

app/views/devise/registrations/_registration.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/sessions/pick_user.html.erb, frontend/components/PasswordInput.js
ajouter sur les champs mot de passe une icone oeil pour voir la visibilité (inscription et connexion -> cf ticket 1183)
=> ELVIS-1182-Inscription-mdp

app/controllers/payments_controller.rb
Utilisateur payeur indiqué comme non payeur
=> ELVIS-1130--Bug-Payer

frontend/components/PacksApplications/MyActivities/myActivities.js
[Accueil] pbm affichage
Le bloc se retrouve décalé sur la page d'accueil
=> ELVIS-1203

frontend/components/stepzilla.css
[Stepper] Retours stepper
Diminuer la taille du rond et la mettre à 40p à la place de 50px
Texte des étapes à passer en 12px
Essayer de voir pour se rapprocher au maximum de la maquette (position des étapes, mise en page des points) et si ce n'est pas concluant supprimer les points entre les étapes et réduire l'espace entre chaque point de l'étape et voir pour que le premier point soit aligner à gauche.
=> ELVIS-1204

frontend/components/courses/AddLocationForCourse.js
Lise de Tous en Scène a voulu créer un cours depuis la liste des cours mais le lieu n'est pas repris et bloque la création du cours.
=> ELVIS-1208

frontend/components/courses/AddTeacherForCourse.js
[Ajouter un cours] pbm choix professeur quand revient à l'étape précédente
url : https://ecoledutango.callingelvis.com/addCourse
J'ai commencé à saisir des informations dans le parcours de création, je suis sur la dernière étape. Je reviens sur l'étape 3 choix professeur, je ne peux pas revenir à l'étape suivante. On me demande de choisir un professeur alors que c'est déjà le cas.
=> ELVIS-1210

app/controllers/activities_applications_controller.rb, app/controllers/application_controller.rb, app/models/activity.rb, app/models/activity_instance.rb, app/models/activity_ref.rb, app/models/parameter.rb, app/models/season.rb, app/models/time_interval.rb, app/services/activity_applications/find_activity_suggestions.rb, app/services/utils.rb, config/initializers/30-elvis.rb, frontend/components/activityApplications/summary/Summary.js, lib/elvis/cache_utils.rb, lib/elvis/version.rb
The Activity (show) application page could take more than 10s to load. Optimized the page by reducing the number of SQL queries (+2900 => 500) and removing unnecessary code / functionality (refetch in loadData...).
Introduction of caching utilities with activation and duration saved in the database.
=> Optimize activity application page

app/controllers/activities_applications_controller.rb, app/models/activity_application.rb, app/services/new_student_level_questionnaires/create_with_answers.rb
Remove beginner level if user has practiced the instrument
=> ZIGGY- 939-- Activity-Level

frontend/components/PacksApplications/MyActivities/myActivities.js
Afficher le bloc d'inscription si les inscriptions sont ouvertes (pour la saison actuelle ou suivnte)
=> ELVIS-1186

app/views/users/edit_password.html.erb
Remplacer le texte : définissez votre mot de passe
=> ELVIS-1199--text-edit-password

frontend/components/editParameters/SchoolParameters.js
problème affichage button "enregistrer"
=> ELVIS-1198--affichage-parameters-school

frontend/components/userForm/GeneralInfos.js, frontend/tools/validators.js
[Coordonnées] message d'erreur civilité
Ajouter en dessous le message d'erreur : cette information est requise à la place d'err_required
=> ZIGGY-916--UserForm-err_required

frontend/components/ActivitiesApplicationsList.js
Lorsque je sélectionne la totalité des demandes via "sélectionner les restantes", le bouton d'envoi de mail en masse disparait.
(la méthode "statusFilterContainsTerminalStatus" n'est pas réévaluée correctement)
=> ELVIS-1211--Demande-inscription-mail

frontend/components/activityRef/ActivityRefDataService.js
[Activités] Tarifs - les données sont bien enregistrées mais la liste n'est pas rafraichie
=> ZIGGY-925--Tarifs-reload

app/controllers/activity_ref_controller.rb
[Activité] trier le select famille par ordre alphabétique
=> ELVIS-1034

app/controllers/activities_applications_controller.rb, config/routes.rb, frontend/components/ActivitiesApplicationsList.js
[Demandes d'inscription] mise en place suppression de masse
Sur la vue liste des demandes d'inscription, je sélectionne plusieurs ou une case à cocher devant la demande, afficher le bouton supprimer (même fonctionnement que sur la page suivi de paiement https://ecoledutango.callingelvis.com/payments).
=> ELVIS-1214-Demandes-Inscription-bulkdelete

app/controllers/activity_ref_controller.rb, frontend/components/activityRef/ActivityRefApplication.js, frontend/components/activityRef/ActivityRefContainer.js
Inscription] mettre par défaut dissocier l'activité
Par défaut, mettre comme paramétrage au niveau de l'inscription : "dissocier l'activité à la place de rattacher à l'activité", demander à l'élève de saisir ses disponibilités.
=> ELVIS-1231--Inscription-default

app/controllers/parameters_controller.rb
Ajouter un nouvel encart sur la page paramètres des écoles :
Titre : Notification
Texte : Paramétrez et modifiez vos templates emails.
=> ELVIS-1237--Param-notification-mail

app/views/devise/passwords/new.html.erb
Ne prendre que l'adresse email pour réinitialiser le mot de passe.
=> ZIGGY-861--Mdp-Oublié

frontend/components/availability/AvailabilityManager.js
Supprimer une disponibilité horaire - Ziggy ne supprime pas la bonne !
=> ZIGGY-932--Bug-TimePreferences

frontend/components/planning/RawPlanning.js
Sur la vue bloc, la semaine commence le mardi à la place du lundi.
=> ELVIS-1255--Planning-Bloc-Semaine

frontend/components/PayerPaymentTerms.js, frontend/components/WrappedPayerPaymentTerms.js, frontend/components/activityApplications/Wizard.js
1. rendre obligatoire la déclaration d'un payeur
2. cas Belgique : renseigner le numéro d'identification du payeur si l'élève est mineur, le rendre obligatoire
=> ELVIS-1243--CasinoDeVivegnis-Identification

app/controllers/activities_applications_controller.rb, frontend/components/ActivitiesApplicationsList.js
- Ne pas pouvoir supprimer les demandes avec des cours attribués. si un élève est associé à un cours, il est impossible de supprimer la demande d'inscription.
- Si je sélectionne des demandes avec un cours attribué, le bouton supprimer n'apparait pas.
- Le message bleu "vous avez sélectionné une demande" apparait encore alors que la demande a été supprimé.
- Avant la suppression modifier les informations de la modale : Voulez-vous supprimer la demande ou le {nombre de demandes} sélectionnées. Mettre le Btn annuler (à la place de cancel) à gauche, supprimer à droite cf capture
- Pouvoir désélectionner la sélection totale.
=> ELVIS-1260--inscriptions-bulk-delete

app/controllers/activities_applications_controller.rb, app/controllers/application_controller.rb, app/models/abilities/activity_application_abilities.rb, app/models/ability.rb, app/views/activities_applications/index.html.erb, app/views/activities_applications/show.html.erb, config/initializers/20-menu_generator.rb, config/routes.rb, frontend/components/ActivitiesApplicationsList.js, frontend/components/parameters/ActivityApplications/ApplicationParameters.js
Ajouter un paramétrage, une case à cocher "le professeur peut gérer ses demandes d'inscription"
=> ELVIS-1250-teacher-can-manage-activity-applications
